/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // ── MD3 Surface hierarchy ─────────────────────────────────────────
        "surface": "#f4f6ff",
        "surface-bright": "#f4f6ff",
        "surface-dim": "#bfd6f9",
        "surface-variant": "#c9deff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eaf1ff",
        "surface-container": "#dce9ff",
        "surface-container-high": "#d3e4ff",
        "surface-container-highest": "#c9deff",
        "surface-tint": "#4647d3",
        "background": "#f4f6ff",
        "on-surface": "#212f42",
        "on-surface-variant": "#4e5c71",
        "on-background": "#212f42",
        "inverse-surface": "#010f20",
        "inverse-on-surface": "#8f9eb4",
        // ── MD3 Primary ───────────────────────────────────────────────────
        "primary": {
          DEFAULT: "#4647d3",
          50: "#eaf1ff",
          100: "#dce9ff",
          200: "#d3e4ff",
          300: "#9396ff",
          400: "#8387ff",
          500: "#4647d3",
          600: "#3939c7",
          700: "#3939c7",
          800: "#0a0081",
          900: "#0e009d",
        },
        "primary-dim": "#3939c7",
        "primary-fixed": "#9396ff",
        "primary-fixed-dim": "#8387ff",
        "primary-container": "#9396ff",
        "on-primary": "#f4f1ff",
        "on-primary-container": "#0a0081",
        "on-primary-fixed": "#000000",
        "on-primary-fixed-variant": "#0e009d",
        "inverse-primary": "#8083ff",
        // ── MD3 Secondary (Green = completion/success) ────────────────────
        "secondary": "#006a2d",
        "secondary-dim": "#005d26",
        "secondary-fixed": "#6bff8f",
        "secondary-fixed-dim": "#5bf083",
        "secondary-container": "#6bff8f",
        "on-secondary": "#ceffd0",
        "on-secondary-container": "#005f28",
        "on-secondary-fixed": "#004a1d",
        "on-secondary-fixed-variant": "#006a2d",
        // ── MD3 Tertiary (Gold = points/rewards) ─────────────────────────
        "tertiary": "#745700",
        "tertiary-dim": "#654c00",
        "tertiary-fixed": "#fdc425",
        "tertiary-fixed-dim": "#edb60f",
        "tertiary-container": "#fdc425",
        "on-tertiary": "#fff1da",
        "on-tertiary-container": "#574000",
        "on-tertiary-fixed": "#3f2e00",
        "on-tertiary-fixed-variant": "#624900",
        // ── MD3 Outline ───────────────────────────────────────────────────
        "outline": "#6a788d",
        "outline-variant": "#a0aec5",
        // ── MD3 Error (Red = danger/miss) ─────────────────────────────────
        "error": "#b41340",
        "error-dim": "#a70138",
        "error-container": "#f74b6d",
        "on-error": "#ffefef",
        "on-error-container": "#510017",
        // ── Semantic aliases for backward compatibility ───────────────────
        "danger": "#b41340",
        "success": {
          DEFAULT: "#006a2d",
          light: "#6bff8f",
          dark: "#004a1d",
        },
        "warning": {
          DEFAULT: "#F59E0B",
          light: "#FEF3C7",
          dark: "#B45309",
        },
        "gold": {
          DEFAULT: "#fdc425",
          light: "#FEF9C3",
          dark: "#574000",
        },
      },
      fontFamily: {
        sans: ["Be Vietnam Pro", "system-ui", "sans-serif"],
        body: ["Be Vietnam Pro", "system-ui", "sans-serif"],
        headline: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        label: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        sm: "0.5rem",
        md: "1rem",
        lg: "2rem",
        xl: "3rem",
        "2xl": "2rem",
        "3xl": "3rem",
        full: "9999px",
      },
      backgroundImage: {
        "primary-gradient": "linear-gradient(135deg, #4647d3 0%, #9396ff 100%)",
        "hero-gradient": "linear-gradient(135deg, #4647d3 0%, #9396ff 100%)",
        "dark-gradient": "linear-gradient(180deg, #1A1A2E 0%, #0D0D1A 100%)",
      },
      boxShadow: {
        "cloud": "0 10px 30px rgba(33, 47, 66, 0.08)",
        "cloud-lg": "0 20px 60px rgba(33, 47, 66, 0.08)",
        "primary-glow": "0 8px 25px rgba(70, 71, 211, 0.3)",
        "glow": "0 0 20px rgba(70, 71, 211, 0.4)",
        "glow-gold": "0 0 20px rgba(253, 196, 37, 0.4)",
        "glow-success": "0 0 20px rgba(0, 106, 45, 0.4)",
        "glass": "0 8px 32px rgba(33, 47, 66, 0.1)",
      },
      animation: {
        "bounce-in": "bounceIn 0.5s cubic-bezier(0.175, 0.885, 0.32, 1.275)",
        "fade-up": "fadeUp 0.4s ease-out",
        "pulse-glow": "pulseGlow 2s ease-in-out infinite",
        "spin-slow": "spin 3s linear infinite",
      },
      keyframes: {
        bounceIn: {
          "0%": { transform: "scale(0.3)", opacity: "0" },
          "50%": { transform: "scale(1.05)" },
          "70%": { transform: "scale(0.9)" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
        fadeUp: {
          "0%": { transform: "translateY(20px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        pulseGlow: {
          "0%, 100%": { boxShadow: "0 0 20px rgba(70, 71, 211, 0.4)" },
          "50%": { boxShadow: "0 0 40px rgba(70, 71, 211, 0.8)" },
        },
      },
    },
  },
  plugins: [],
}
